services:
  mariadb:
    image: bitnami/mariadb:11.4.5
    environment:
      MARIADB_ROOT_PASSWORD: "${SQUAT_DB_ROOT_PASSWORD}"
      MARIADB_USER: "${SQUAT_DB_USER}"
      MARIADB_PASSWORD: "${SQUAT_DB_PASSWORD}"
      MARIADB_DATABASE: "${SQUAT_DB_DATABASE}"
    ports:
      - "${SQUAT_DB_PORT}:${SQUAT_DB_PORT}"
    volumes:
      - mariadb_data:/bitnami/mariadb/data
    networks:
      - app-network

volumes:
  mariadb_data:
    driver: local
  redis_data:
    driver: local
  rabbitmq-lib:

networks:
  pumped-network:
    external: true
  app-network:
    driver: bridge