services:
  mariadb:
    image: bitnami/mariadb:11.4.5
    environment:
      MARIADB_ROOT_PASSWORD: "${BB_DB_ROOT_PASSWORD}"
      MARIADB_USER: "${BB_DB_USER}"
      MARIADB_PASSWORD: "${BB_DB_PASSWORD}"
      MARIADB_DATABASE: "${BB_DB_DATABASE}"
    ports:
      - "${BB_DB_PORT}:${BB_DB_PORT}"
    volumes:
      - mariadb_data:/bitnami/mariadb/data
    networks:
      - app-network

volumes:
  mariadb_data:
    driver: local
  redis_data:
    driver: local
  rabbitmq-lib:

networks:
  pumped-network:
    external: true
  app-network:
    driver: bridge